name: "HACS Action"

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron:  "0 0 * * *"

jobs:
  hacs:
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.2.2"
        - name: "Run HACS validation"
          uses: "hacs/action@main"
          with:
            category: "integration"
